### ISSUE TITLE
找不到'/sqchen/code/spcolor/saved_models/cocostuff27_vit_base_5.ckpt'

### ISSUE THREAD

**Issue by JstYY** [viector/spcolor#1]
您好，我在运行程序后stego_segmentation.py文件的44行出现找不到model = LitUnsupervisedSegmenter.load_from_checkpoint("/sqchen/code/spcolor/saved_models/cocostuff27_vit_base_5.ckpt")这个路径下的模型，我看了代码也没有找到是在哪里下载的，麻烦您可以说一下这个模型的来源吗，十分感谢！！！

**Comment by viector** [comment]
hi 你好， STEGO模型来源于：
https://paperswithcode.com/paper/unsupervised-semantic-segmentation-by-2
这篇文章。
你可以在链接的github repo里找到需要的ckpt。





&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Apr 8, 2024 03:28 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[viector/spcolor] 找不到'/sqchen/code/spcolor/saved_models/cocostuff27_vit_base_5.ckpt' (Issue #1)

&nbsp;



 
您好，我在运行程序后stego_segmentation.py文件的44行出现找不到model = LitUnsupervisedSegmenter.load_from_checkpoint("/sqchen/code/spcolor/saved_models/cocostuff27_vit_base_5.ckpt")这个路径下的模型，我看了代码也没有找到是在哪里下载的，麻烦您可以说一下这个模型的来源吗，十分感谢！！！

**Comment by haofengl** [comment]
hello, 想问下数据集是怎么制作的？或者可以介绍下数据集嘛

**Comment by viector** [comment]
关于数据集，是按照这篇文章的方法来做的：https://dl.acm.org/doi/abs/10.1145/3197517.3201365
关于ckpt，来自于这个github repo：https://github.com/mhamilton723/STEGO

**Comment by haofengl** [comment]
非常感谢您能回复！
您可以提供下conda环境中详细配置吗？可能是tensorboard和其他版本的冲突问题，我总是遇到以下错误：

  FutureWarning,
Traceback (most recent call last):
  File "train_stego.py", line 38, in <module>
    from stego_models.stego_segmentation import STEGO_seg
  File "/home/work/liuhaofeng/spcolor/stego_models/stego_segmentation.py", line 8, in <module>
    from train_segmentation import LitUnsupervisedSegmenter
  File "/home/work/liuhaofeng/spcolor/stego_models/train_segmentation.py", line 9, in <module>
    import pytorch_lightning as pl
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 39, in <module>
    from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/trainer/__init__.py", line 16, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 30, in <module>
    from pytorch_lightning.accelerators import Accelerator, IPUAccelerator
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/accelerators/__init__.py", line 13, in <module>
    from pytorch_lightning.accelerators.accelerator import Accelerator  # noqa: F401
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 26, in <module>
    from pytorch_lightning.plugins.precision import ApexMixedPrecisionPlugin, NativeMixedPrecisionPlugin, PrecisionPlugin
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/__init__.py", line 8, in <module>
    from pytorch_lightning.plugins.plugins_registry import (  # noqa: F401
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/plugins_registry.py", line 20, in <module>
    from pytorch_lightning.plugins.training_type.training_type_plugin import TrainingTypePlugin
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/__init__.py", line 13, in <module>
    from pytorch_lightning.plugins.training_type.tpu_spawn import TPUSpawnPlugin  # noqa: F401
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py", line 27, in <module>
    from pytorch_lightning.loggers import LoggerCollection, TensorBoardLogger
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/loggers/__init__.py", line 18, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 23, in <module>
    serialized_pb=_b('\n+tensorboard/compat/proto/tensor_shape.proto\x12\x0btensorboard\"{\n\x10TensorShapeProto\x12.\n\x03\x64im\x18\x02 \x03(\x0b\x32!.tensorboard.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
  File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 983, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/compat/proto/tensor_shape.proto":
  tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.unknown_rank: "tensorboard.TensorShapeProto.unknown_rank" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim.size: "tensorboard.TensorShapeProto.Dim.size" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim.name: "tensorboard.TensorShapeProto.Dim.name" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.Dim: "tensorboard.TensorShapeProto.Dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto: "tensorboard.TensorShapeProto" is already defined in file "tensorboardX/src/tensor_shape.proto".
  tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.Dim" seems to be defined in "tensorboardX/src/tensor_shape.proto", which is not imported by "tensorboard/compat/proto/tensor_shape.proto".  To use it here, please add the necessary import.

**Comment by viector** [comment]
hi，

conda 环境配置在 github repo 中： https://github.com/viector/spcolor/blob/main/environment.yml
如果按照上面的配置有问题，可以试试附件里的yaml。这是我最近在用的环境，但因为做了些其他实验，可能有一些多余的库。

&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Dec 17, 2024 04:09 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [viector/spcolor] 找不到'/sqchen/code/spcolor/saved_models/cocostuff27_vit_base_5.ckpt' (Issue #1)

&nbsp;



 
非常感谢您能回复！
 您可以提供下conda环境中详细配置吗？可能是tensorboard和其他版本的冲突问题，我总是遇到以下错误：
 
FutureWarning,
 Traceback (most recent call last):
 File "train_stego.py", line 38, in 
 from stego_models.stego_segmentation import STEGO_seg
 File "/home/work/liuhaofeng/spcolor/stego_models/stego_segmentation.py", line 8, in 
 from train_segmentation import LitUnsupervisedSegmenter
 File "/home/work/liuhaofeng/spcolor/stego_models/train_segmentation.py", line 9, in 
 import pytorch_lightning as pl
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/init.py", line 20, in 
 from pytorch_lightning.callbacks import Callback  # noqa: E402
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/callbacks/init.py", line 26, in 
 from pytorch_lightning.callbacks.pruning import ModelPruning
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in 
 from pytorch_lightning.core.lightning import LightningModule
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/core/init.py", line 16, in 
 from pytorch_lightning.core.lightning import LightningModule
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 39, in 
 from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/trainer/init.py", line 16, in 
 from pytorch_lightning.trainer.trainer import Trainer
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 30, in 
 from pytorch_lightning.accelerators import Accelerator, IPUAccelerator
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/accelerators/init.py", line 13, in 
 from pytorch_lightning.accelerators.accelerator import Accelerator  # noqa: F401
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 26, in 
 from pytorch_lightning.plugins.precision import ApexMixedPrecisionPlugin, NativeMixedPrecisionPlugin, PrecisionPlugin
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/init.py", line 8, in 
 from pytorch_lightning.plugins.plugins_registry import (  # noqa: F401
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/plugins_registry.py", line 20, in 
 from pytorch_lightning.plugins.training_type.training_type_plugin import TrainingTypePlugin
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/init.py", line 13, in 
 from pytorch_lightning.plugins.training_type.tpu_spawn import TPUSpawnPlugin  # noqa: F401
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/tpu_spawn.py", line 27, in 
 from pytorch_lightning.loggers import LoggerCollection, TensorBoardLogger
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/loggers/init.py", line 18, in 
 from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in 
 from torch.utils.tensorboard import SummaryWriter
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/torch/utils/tensorboard/init.py", line 13, in 
 from .writer import FileWriter, SummaryWriter  # noqa: F401
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 9, in 
 from tensorboard.compat.proto.event_pb2 import SessionLog
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in 
 from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in 
 from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in 
 from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in 
 from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 23, in 
 serialized_pb=_b('\n+tensorboard/compat/proto/tensor_shape.proto\x12\x0btensorboard"{\n\x10TensorShapeProto\x12.\n\x03\x64im\x18\x02 \x03(\x0b\x32!.tensorboard.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
 File "/root/miniforge3/envs/spcolor0/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 983, in new
 return _message.default_pool.AddSerializedFile(serialized_pb)
 TypeError: Couldn't build proto file into descriptor pool!
 Invalid proto descriptor for file "tensorboard/compat/proto/tensor_shape.proto":
 tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
 tensorboard.TensorShapeProto.unknown_rank: "tensorboard.TensorShapeProto.unknown_rank" is already defined in file "tensorboardX/src/tensor_shape.proto".
 tensorboard.TensorShapeProto.Dim.size: "tensorboard.TensorShapeProto.Dim.size" is already defined in file "tensorboardX/src/tensor_shape.proto".
 tensorboard.TensorShapeProto.Dim.name: "tensorboard.TensorShapeProto.Dim.name" is already defined in file "tensorboardX/src/tensor_shape.proto".
 tensorboard.TensorShapeProto.Dim: "tensorboard.TensorShapeProto.Dim" is already defined in file "tensorboardX/src/tensor_shape.proto".
 tensorboard.TensorShapeProto: "tensorboard.TensorShapeProto" is already defined in file "tensorboardX/src/tensor_shape.proto".
 tensorboard.TensorShapeProto.dim: "tensorboard.TensorShapeProto.Dim" seems to be defined in "tensorboardX/src/tensor_shape.proto", which is not imported by "tensorboard/compat/proto/tensor_shape.proto".  To use it here, please add the necessary import.

**Comment by tiezu** [comment]
> 您好，我在运行程序后stego_segmentation.py文件的44行出现找不到model = LitUnsupervisedSegmenter.load_from_checkpoint("/sqchen/code/spcolor/saved_models/cocostuff27_vit_base_5.ckpt")这个路径下的模型，我看了代码也没有找到是在哪里下载的，麻烦您可以说一下这个模型的来源吗，十分感谢！！！

您好，我想请问一下您的数据集是怎样的组织结构，我试图采用miniimagenet进行训练但是不太行
